CREATE TABLE "HR"."NOTICE" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
   
   -- 추천게시판(RECOMMEND)
   --RE_NO 숫자
   --TITLE, CONTENT
   --WRITER 문자
   
   CREATE TABLE HR.RECOMMEND
   (	"RE_NO" NUMBER(38,0),
   	"TITLE" VARCHAR2(100),
   	"CONTENT" VARCHAR2(100),
   	"WRITER" VARCHAR2(100)
   )
   
  DROP TABLE HR.RECOMMEND -- 테이블 통채로 삭제
   
   CREATE TABLE HR.RECOMMEND
   (	"RE_NO" NUMBER(38,0),
   	"TITLE" VARCHAR2(100),
   	"CONTENT" VARCHAR2(100),
   	"WRITER" VARCHAR2(100)
   )
   
  	ALTER TABLE HR.RECOMMEND MODIFY TITLE VARCHAR2(200);
 
	ALTER TABLE HR.RECOMMEND MODIFY CONTENT VARCHAR2(300);

SELECT *FROM HR.RECOMMEND

	ALTER TABLE HR.RECOMMEND ADD TEST1 VARCHAR2(100) NULL;

	ALTER TABLE HR.RECOMMEND ADD TEST2 VARCHAR2(100) NULL;

	ALTER TABLE HR.RECOMMEND ADD TEST3 VARCHAR2(100) NULL;

CREATE TABLE "HR"."BOARD3" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
   ALTER TABLE BOARD3 MODIFY WRITER VARCHAR2(200)
   
   ALTER TABLE BOARD3 DROP COLUMN VIEWCOUNT
   
   ALTER TABLE BOARD3 ADD TEST2 VARCHAR2(100)
   
   DROP TABLE HR.BOARD3 
   
   CREATE TABLE "HR"."PRODUCT222" 
   ("ID" VARCHAR2(100) PRIMARY key, 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
   )
   
  CREATE TABLE "HR"."PRODUCT3" 
   ("ID" VARCHAR2(100) PRIMARY key, 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
   )
   

   
   --DCL : DB관리 제어해주는 문법 계정생성, 계정권한부여, 백업, 복구
   
   
   GRANT CONNECT, resource, dba TO apple
   
 
  CREATE USER apple IDENTIFIED BY a1234
  
  CREATE USER scott
  IDENTIFIED BY tiger;
 GRANT CONNECT, resource, dba TO scott;

INSERT INTO HR.MEMBER VALUES('100','100','PARK','011')

INSERT INTO HR.MEMBER VALUES('200','100','PARK','011')

INSERT INTO HR.MEMBER VALUES('300','100','PARK','011')

SELECT * FROM HR."MEMBER" 

SELECT * FROM HR."MEMBER" WHERE ID='100'--ID가 100인 모든 컬럼

SELECT ID, NAME  FROM HR."MEMBER" WHERE ID='100'--ID가 100인 ID랑NAME 컬럼

SELECT NAME,ID   FROM HR."MEMBER" WHERE ID='100'--ID가 100인 ID랑NAME 컬럼

SELECT ID AS 아이디, NAME FROM HR."MEMBER" WHERE ID='100'

SELECT TEL FROM HR."MEMBER" WHERE NAME = 'PARK'

UPDATE HR.MEMBER SET NAME = 'KIM' WHERE ID = '100'

UPDATE HR.MEMBER SET NAME = 'CHOI' WHERE ID = '200'

UPDATE HR.MEMBER SET NAME = 'LEE' WHERE ID = '300'

SELECT *FROM HR."MEMBER"

UPDATE HR."MEMBER" SET PW = '8888',TEL='9999' WHERE ID = 'ICE'

DELETE FROM HR.MEMBER WHERE ID = '100'

DELETE FROM HR.MEMBER WHERE TEL = '011'

SELECT * FROM HR.MEMBER WHERE id = '200' AND tel = '011'

SELECT * FROM HR.MEMBER WHERE id = '200' or tel = '011'





CREATE TABLE HR.product (
	id varchar2(200), 
	name varchar2(200), 
	content varchar2(200), 
	price varchar2(200), 
	company varchar2(200), 
	img varchar2(200)
)

SELECT * FROM HR."MEMBER" ORDER BY ID 

SELECT * FROM HR.PRODUCT ORDER BY PRICE DESC 

SELECT NAME, CONTENT, PRICE FROM HR.PRODUCT ORDER BY COMPANY ASC 

SELECT NAME, PRICE FROM HR.PRODUCT WHERE ID = '100'

SELECT  NAME, COMPANY FROM HR.PRODUCT WHERE PRICE = '5000'

SELECT  NAME, IMG FROM HR.PRODUCT WHERE ID='100', PRICE = '1000'

SELECT  COMPANY,NAME  FROM HR.PRODUCT WHERE COMPANY ='c100'

SELECT  NAME,PRICE FROM HR.PRODUCT WHERE COMPANY ='c100'OR COMPANY ='c200'

UPDATE HR.PRODUCT SET CONTENT ='품절'WHERE PRICE ='5000'

SELECT * FROM HR.PRODUCT 

UPDATE HR.PRODUCT SET IMG='o.png' ,PRICE = '10000' WHERE ID ='100' OR ID='102'

UPDATE HR.PRODUCT SET COMPANY ='apple',NAME='appleshoes' WHERE ID ='101'

DELETE FROM HR.PRODUCT WHERE NAME ='shoes1'OR ID ='107'

DELETE FROM HR.PRODUCT WHERE COMPANY ='c100'

DELETE FROM HR.PRODUCT 

DROP TABLE HR.PRODUCT 









  
  
  